node {
  def project = 'helmsman-2018'
  def appName = 'gceme'
  def feSvcName = "${appName}-frontend"
  def imageTag = "gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

  checkout scm

  stage 'Build image'
  sh("docker build -t ${imageTag} .")

  stage 'Run Go tests'
  sh("docker run ${imageTag} go test")

  stage 'Push image to registry'
  sh("gcloud docker -- push ${imageTag}")

  stage "Deploy Application"
  switch (env.BRANCH_NAME) {
    // Roll out to canary environment
    case "canary":
        // Change deployed image in canary to the one we just built
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/canary/*.yaml")
        
        sh("echo '***********************************************'")
        sh("echo 'SET CLUSTER CONTEXT TO frontend-dev-app-cluster'")
        sh("echo '***********************************************'")

        sh("kubectl config set-credentials admin/35.224.199.159 --username=admin --password=lp4GX9QJifxa7sxa")
        sh("kubectl config set-cluster 35.224.199.159 --insecure-skip-tls-verify=true --server=https://35.224.199.159")
        sh("kubectl config set-context frontend-dev-app-cluster/35.224.199.159/admin --user=admin/35.224.199.159 --namespace=default --cluster=35.224.199.159")
        sh("kubectl config use-context frontend-dev-app-cluster/35.224.199.159/admin")
        
        sh("kubectl --namespace=default apply -f k8s/services/")
        sh("kubectl --namespace=default apply -f k8s/canary/")
        sh("echo http://`kubectl --namespace=default get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")
        sh("echo '***********************************************'")
        sh("echo '**    DONE WITH DEPLOYMENT... GOOD LUCK!     **'")
        sh("echo '***********************************************'")
        break

    // Roll out to production
    case "master":
        // Change deployed image in canary to the one we just built
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/production/*.yaml")
        
        sh("echo '*************************************************'")
        sh("echo 'SET CLUSTER CONTEXT TO frontend-stage-app-cluster'")
        sh("echo '*************************************************'")
        
        sh("kubectl config set-credentials admin/104.197.14.150 --username=admin --password=WIOwpMtFdpalcY0p")
        sh("kubectl config set-cluster 104.197.14.150 --insecure-skip-tls-verify=true --server=https://104.197.14.150")
        sh("kubectl config set-context frontend-stage-app-cluster/104.197.14.150/admin --user=admin/104.197.14.150 --namespace=default --cluster=104.197.14.150")
        sh("kubectl config use-context frontend-stage-app-cluster/104.197.14.150/admin")
        
        sh("kubectl --namespace=default apply -f k8s/services/")
        sh("kubectl --namespace=default apply -f k8s/production/")
        sh("echo http://`kubectl --namespace=default get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")

        sh("echo '***********************************************'")
        sh("echo '**    DONE WITH DEPLOYMENT... GOOD LUCK!     **'")
        sh("echo '***********************************************'")
        break

    // Roll out a dev environment
    default:
        // Create namespace if it doesn't exist
        sh("kubectl get ns ${env.BRANCH_NAME} || kubectl create ns ${env.BRANCH_NAME}")
        // Don't use public load balancing for development branches
        sh("sed -i.bak 's#LoadBalancer#ClusterIP#' ./k8s/services/frontend.yaml")
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/dev/*.yaml")
        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/services/")
        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/dev/")
        echo 'To access your environment run `kubectl proxy`'
        echo "Then access your service via http://localhost:8001/api/v1/proxy/namespaces/${env.BRANCH_NAME}/services/${feSvcName}:80/"
  }
}
