node {
def project = 'helmsman-2018'
def appName = 'db'
def imageTag = "gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

checkout scm

stage 'Build image'
sh("docker build -t ${imageTag} .")

stage 'Run Go tests'
sh("echo 'ok'")

stage 'Push image to registry'
sh("gcloud docker -- push ${imageTag}")
}
