apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-backend-prod
  name: sample-backend-prod
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-sample-backend-prod: "true"
  sessionAffinity: None
  type: LoadBalancer
