{{ if .Values.gke.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-targets
  labels:
    app: {{ template "fullname" . }}
    component: clouddriver
type: Opaque
data:
  {{- range $index, $project := .Values.projects }}
  {{ $project.name }}.json: {{ default "" $project.jsonKey | b64enc | quote }}
  {{- end}}
{{ end }}